---
# This playbook will install mysql and create db user and give permissions.

- name: Install MariaDB package
#AQUI CAMBIAMOS yum por apt (debido que el primero se utiliza en CentOS,
#mientras que apt solemos utilizarlo para Debian Linux.
#APT simplifica en gran medida la instalación y eliminación de programas
#en los sistemas GNU/Linux. )
  apt: name=mariadb-server state=present #mysql est
 
   #- libselinux-python
   #- libsemanage-python

#- name: Configure SELinux to start mysql on any port
#  seboolean: name=mysql_connect_any state=true persistent=yes
#  when: sestatus.rc != 0
- name:  Start Mysql Service
  service: name=mysql state=started enabled=true

- name: Install python Mysql package
  apt: name=python-mysqldb state=present

- name: Install mysql extension for php
  apt: name = {{item}} state:present
  with_items:
    - php5-mysql

- name:  Create a new database
  mysql_db: nomdb={{name}} state=present collation=utf8_general_ci

- name:  Create a database user
  mysql_user: name={{myname}} password={{mypass}} priv=*.*:ALL host=localhost state=present
  
  
