---
# Handler to handle DB tier notifications

# mysqld es un grupo que contiene variable para el cliente es decir, MYSQL.
# Utilzams MariaDB en vez de mysqld porque hubo algunos inconvenientes que no permitieron la instalacion de algunos paquetes
- name: restart MariaDB
  service: name=mariadb state=restarted

- name: restart iptables
  service: name=iptables state=restarted
