---
# These tasks install http and the php modules.

#AQUI CAMBIAMOS yum por apt (debido que el primero se utiliza en CentOS,
#mientras que apt solemos utilizarlo para Debian Linux.
#APT simplifica en gran medida la instalación y eliminación de programas
#en los sistemas GNU/Linux. )

- name: 1. instalacion de Apache2
  apt: name=apache2 state=present

- name: 2. install PHP module for Apache
  apt: name = {{item}} state=present
  with_items :
    -libapache2-mod-php5

- name: 3. start Apache
  service: name=apache2 state=started enabled=yes
  #apt: name={{ item }} state=present
  #with_items:


    # si queremos instalar apache en ubuntu viniendo de CentOS no utilamos
    # httpd sino apache2 para que el lenguaje lo pueda entender y de esta
    #forma su instalacion sea exitosa. Donde veamos httpd cambiamos a apache2
    
