---
# This playbook contains common plays that will be run on all nodes.


#El protocolo NTP es capaz de sincronizar la hora de los equipos con una precisión de milisegundos.
- name: Install ntp
#AQUI CAMBIAMOS yum por apt (debido que el primero se utiliza en CentOS,
#mientras que apt solemos utilizarlo para Debian Linux.
#APT simplifica en gran medida la instalación y eliminación de programas
#en los sistemas GNU/Linux. )
  apt: name=ntp state=present
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=yes
  tags: ntp

#- name: test to see if selinux is running
 # command: getenforce
  #register: sestatus
  #changed_when: false
